test report added

diff --git a/.github/workflows/cypress.yml b/.github/workflows/cypress.yml
--- a/.github/workflows/cypress.yml
+++ b/.github/workflows/cypress.yml
@@ -35,6 +35,36 @@ jobs:
         run: |
           echo "Cypress tests failed. Continuing to generate report."
 
+          # Generate Mochawesome Report
+          npx cypress run --config baseUrl=http://localhost:5173
+
+          # Generate Report Status
+          if [ $? -eq 0 ]; then
+            echo "Test Report Status: Passed"
+          else
+            echo "Test Report Status: Failed"
+          fi
+          export REPORT_STATUS=$(echo)
+
+          # Send Email with Mochawesome Report
+          echo "Sending email with report..."
+
+          uses: dawidd6/action-send-mail@v2 # Assuming the action uses snake_case for outputs
+          with:
+            server_address: 'smtp-mail.outlook.com'
+            server_port: 587
+            username: 'githubreport@outlook.com'
+            password: "'kq'x;u@!n94'sg6W8T`"
+            subject: 'Cypress Test Report (${REPORT_STATUS})' # Use REPORT_STATUS output
+            from: 'githubreport@outlook.com'
+            to: 'ariful.rony10@gmail.com'
+            body: |
+              Please find the attached Mochawesome test report.
+
+              Test results: ${{ steps.Generate_Report_Status.outputs.REPORT_STATUS }}
+            attachments: 'mochawesome-report/mochawesome.json'
+            content_type: 'text/plain'
+
       - name: Generate Mochawesome Report
         run: npx cypress run --config baseUrl=http://localhost:5173
 
